title: SUDAKAS Project
description: Executive Elites in Latin America and Southern Europe
theme: just-the-docs

url: "https://sudakas.github.io"
baseurl: ""

aux_links:
  Repository: "https://github.com/SUDAKAS/sudakas.github.io"

color_scheme: light
